### PR TITLE
add Python 3 compatibility

### PR DESCRIPTION
**Pull request by jonaskluger**
Script is now working in Python 2 and 3.
For Python 2: nothing changes.
For Python 3: all bytes strings get converted to unicode string to be future prove and conform with Python 3 strings.

### CODE REVIEW

**Comment by jonaskluger** [comment]
#2 by 'testing' I meant that it should work probably :-P

But sure, tests for Python 3 will follow!

**Comment by jonaskluger** [comment]
Just added one test that checks the entire metadata dictionary that is returned.
The tests work for Python 2 and Python 3.

**Comment by vvzen** [comment]
Hi @jonaskluger !
thanks for taking the time to write new tests!
I've checked against `Python 2.7.15` and `Python 3.8.2` and they're all passing.
If you can stick to PEP8 that would be great, otherwise I'll run my formatter (`yapf`) after I've merged the branch.
Let me know when I can merge it, I was planning of adding a small CLI to go along with this repo.
Thanks!

**Comment by jonaskluger** [comment]
I did format the files.
Cheers!

**Pull request merged**
