### PR TITLE
Add [0] in several places where it had been ommitted.

### PR DESCRIPTION
**Pull request by barkofdelight**
pixel type, sampling, preview and timecode. Also this fixed a potential
crash with the use of the width and height values for the preview.

### CODE REVIEW

**Comment by vvzen** [comment]
Hi @barkofdelight !

Sorry for the delay and thanks for your contribution :D
I haven't yet had time to look (and understand) at the changes, but I ran the tests and they're not passing. Did you ran them too?

Also - if you don't mind, I'm trying to keep the commit style closer to this: https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53 just for the sake of convention.

Thanks!

vv

**Comment by barkofdelight** [comment]
Hi!

Oops, yes of course I didn't expect tests. ;)

You're right, the changes absolutely break the tests. I would claim that the new results are correct and the previous are incorrect.

Specifically, the old looks like this:

`
                    'pLinear': (0, ),
                    'pixel_type': (1, ),
                    'xSampling': (1, ),
                    'ySampling': (1, )
`

And the new:

`
                    'pLinear': 0,
                    'pixel_type': 1,
                    'xSampling': 1,
                    'ySampling': 1
`

That is to say, these fields are being returned as integers instead of tuples.

Do you agree?

As to the commit message, can I change that after I've pushed it to GitHub, or do I have to make a new branch or something awkward like that?

Thanks.

**Comment by vvzen** [comment]
Hi again!

So I had to quickly check against the reference PDF (https://www.openexr.com/documentation/openexrfilelayout.pdf) to be sure there wasn't anything funky going on. For a moment, I wondered if it didn't make sense to actually return a tuple everywhere to make the API immutable by default (since we're just reading metadata, no-one should change the data by mistake).

Anyways for `chlist` (channel list), the OpenEXR File Layout PDF mentions:

```
A sequence of channels followed by a null byte (0x00).

Channel layout:
    name         zero-terminated string, from 1 to 255 bytes long
    pixel type   int, possible values are:
                                 UINT=0
                                 HALF=1
                                 FLOAT=2
    pLinear      unsigned char, possible values are 0 and 1
    reserved     three chars, should be zero
    xSampling    int
    ySampling    int
``` 

For now, to keep it simple, it may make sense to return just integers instead of tuples with size==1. 
If you want to go for it, please do! But update the tests as well since this is a breaking change in behaviour.

Regarding the commit, I recommend to have a look at some git intro tutorials, but basically you can `git commit --amend` and change the commit message locally and then do a force push on your own local and remote fork/branch.

Thanks!

vv

**Comment by barkofdelight** [comment]
Ok, I've updated the test and commit message.

> For a moment, I wondered if it didn't make sense to actually return a tuple everywhere

This of course is an option—as long as there's consistency. But my opinion is that you should return plain values whenever possible.

**Comment by vvzen** [comment]
Thank you!

I have merged the changes now.

**Pull request merged**
